#!/usr/bin/env python3
"""
TradeVerse Render Deployment - Quick Setup Assistant

This script provides everything needed to deploy to Render.
It generates the exact commands and configuration needed.
"""

import sys
import json
from pathlib import Path
from datetime import datetime

def print_header(text):
    """Print a formatted header"""
    print("\n" + "=" * 80)
    print(f"  {text}")
    print("=" * 80 + "\n")

def print_section(text):
    """Print a formatted section header"""
    print(f"\n{'-' * 80}")
    print(f"  {text}")
    print(f"{'-' * 80}\n")

def main():
    """Main deployment guide"""
    
    print_header("TradeVerse - Render Deployment Setup")
    print(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    # GitHub Repository Info
    print_section("1. GITHUB REPOSITORY")
    repo_url = "https://github.com/Nathan30302/TradeVerse"
    print(f"Repository: {repo_url}")
    print(f"Branch: main")
    print(f"Status: Ready for deployment ✓")
    
    # Render Web Service Configuration
    print_section("2. RENDER WEB SERVICE CONFIGURATION")
    
    web_config = {
        "name": "tradeverse",
        "runtime": "Python 3",
        "buildCommand": "pip install -r requirements.txt",
        "startCommand": "gunicorn -w 4 -b 0.0.0.0:$PORT app.wsgi:app",
        "region": "Oregon (US) - Free tier",
        "plan": "Free (0.5 CPU, 512MB RAM)"
    }
    
    for key, value in web_config.items():
        print(f"{key:20} : {value}")
    
    # Render Database Configuration
    print_section("3. RENDER POSTGRESQL CONFIGURATION")
    
    db_config = {
        "name": "tradeverse-db",
        "database": "tradeverse",
        "user": "tradeverse_user",
        "engine": "PostgreSQL 15",
        "plan": "Free (0.5GB storage)"
    }
    
    for key, value in db_config.items():
        print(f"{key:20} : {value}")
    
    # Environment Variables
    print_section("4. ENVIRONMENT VARIABLES (Set in Render)")
    
    env_vars = {
        "FLASK_ENV": "production",
        "SECRET_KEY": "[Auto-generated by Render or set custom]",
        "DATABASE_URL": "[Auto-linked from PostgreSQL instance]",
        "PYTHONUNBUFFERED": "true"
    }
    
    for key, value in env_vars.items():
        print(f"  {key:25} = {value}")
    
    # Step-by-Step Deployment
    print_section("5. DEPLOYMENT STEPS (DO THIS IN RENDER UI)")
    
    steps = [
        ("1", "Go to https://render.com/", "Create free account"),
        ("2", "Click 'New' → 'Web Service'", ""),
        ("3", "Connect GitHub account", "Authorize Render"),
        ("4", "Select 'Nathan30302/TradeVerse'", "Main branch"),
        ("5", "Enter Name", "tradeverse"),
        ("6", "Select Runtime", "Python 3"),
        ("7", "Build Command", "pip install -r requirements.txt"),
        ("8", "Start Command", "gunicorn -w 4 -b 0.0.0.0:$PORT app.wsgi:app"),
        ("9", "Region", "Oregon (US)"),
        ("10", "Plan", "Free (do NOT select paid)"),
        ("11", "Click 'Create Web Service'", "Wait 2-3 minutes for build"),
        ("12", "Once deployed, go to 'New'", "PostgreSQL"),
        ("13", "PostgreSQL Setup", "See database config above"),
        ("14", "Link Database", "Go to web service → Environment"),
        ("15", "Add DATABASE_URL", "Copy from PostgreSQL instance"),
        ("16", "Save Environment", "Render auto-redeploys"),
        ("17", "Check Logs", "Monitor build and deployment"),
        ("18", "Get Public URL", "Format: https://tradeverse-xxxx.onrender.com")
    ]
    
    for step_num, action, detail in steps:
        if detail:
            print(f"  Step {step_num:2} : {action:30} ({detail})")
        else:
            print(f"  Step {step_num:2} : {action:30}")
    
    # Database Initialization (Post-Deployment)
    print_section("6. POST-DEPLOYMENT DATABASE SETUP")
    print("After web service is live:")
    print()
    print("  Option A - Via Render Shell Tab (Recommended):")
    print("    1. Go to Web Service → Shell tab")
    print("    2. Run: flask db upgrade")
    print("    3. Database tables are created automatically")
    print()
    print("  Option B - Automatic (Preferred for production):")
    print("    The app auto-creates tables on first startup")
    print()
    
    # Application Features
    print_section("7. DEPLOYED APPLICATION FEATURES")
    features = [
        "User authentication (signup, login, logout)",
        "Trading journal - Create, edit, delete trades",
        "Trade plans - Plan trades before execution",
        "Performance metrics - Win rate, P&L analysis",
        "Dashboard - Charts and trading statistics",
        "Multiple trading instruments support",
        "Risk management and position sizing",
        "Trade feedback and sentiment tracking",
        "Responsive design (mobile-friendly)"
    ]
    
    for i, feature in enumerate(features, 1):
        print(f"  {i}. {feature}")
    
    # Monitoring & Troubleshooting
    print_section("8. MONITORING & TROUBLESHOOTING")
    
    monitoring = [
        ("Check Build Logs", "Web Service → Logs → Build Log", "See compilation errors"),
        ("Check Deploy Logs", "Web Service → Logs → Deploy Log", "See startup errors"),
        ("Check Runtime Logs", "Web Service → Logs (latest)", "See application output"),
        ("Database Connection", "Check DATABASE_URL is set", "Must be in Environment vars"),
        ("Static Files", "Visit site, open DevTools", "CSS/JS should load from /static"),
        ("Live Status", "Render Dashboard", "Shows service health and uptime")
    ]
    
    for check, location, notes in monitoring:
        print(f"  • {check:20} : {location:40} ({notes})")
    
    # Test the Deployment
    print_section("9. TEST YOUR DEPLOYMENT")
    
    tests = [
        "Open the URL in browser (https://tradeverse-xxxx.onrender.com)",
        "Create a test user account (signup)",
        "Log in with test credentials",
        "Create a test trade",
        "Check dashboard for the trade",
        "Verify data persists (refresh page)",
        "Test logout and login again",
        "Confirm your trade is still there"
    ]
    
    for i, test in enumerate(tests, 1):
        print(f"  {i}. {test}")
    
    # Final Notes
    print_section("10. IMPORTANT NOTES")
    
    notes = [
        ("Free Tier", "Web service sleeps after 15 min inactivity (takes 30s to wake)"),
        ("Data Persistence", "PostgreSQL database persists data permanently"),
        ("File Uploads", "Trade screenshots stored in /tmp (ephemeral - not permanent)"),
        ("HTTPS", "Automatically provided by Render (*.onrender.com domain)"),
        ("Environment", "Application runs in production mode (DEBUG=False)"),
        ("Logging", "Check Render logs for any errors or warnings"),
        ("Scaling", "Free tier limited to 1 web service + 1 database")
    ]
    
    for title, description in notes:
        print(f"  • {title:18} : {description}")
    
    # Support & Documentation
    print_section("11. SUPPORT & DOCUMENTATION")
    
    support = [
        ("Render Docs", "https://render.com/docs"),
        ("Flask Docs", "https://flask.palletsprojects.com/"),
        ("GitHub Issues", "https://github.com/Nathan30302/TradeVerse/issues"),
        ("Application", "https://github.com/Nathan30302/TradeVerse")
    ]
    
    for resource, url in support:
        print(f"  • {resource:18} : {url}")
    
    # Summary
    print_section("SUMMARY")
    
    print("[OK] Production configuration: READY")
    print("[OK] GitHub repository: PUSHED")
    print("[OK] Dependencies: CONFIGURED")
    print("[OK] Database migrations: READY")
    print()
    print("[READY] YOUR APPLICATION IS READY TO DEPLOY TO RENDER!")
    print()
    print("Next steps:")
    print("  1. Go to https://render.com")
    print("  2. Follow the step-by-step instructions above (Section 5)")
    print("  3. Once deployed, bookmark your public URL")
    print("  4. Share the URL with users (it's live and public!)")
    print()
    
    print_header("Deployment Complete")
    print("Estimated deployment time: 5-10 minutes (first time)")
    print("Application uptime: Free tier (with sleep after 15 min inactivity)")
    print()

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nDeployment guide cancelled.")
        sys.exit(1)
    except Exception as e:
        print(f"\n[ERROR] Error: {e}")
        sys.exit(1)
