"""initial schema

Revision ID: 07e766313e36
Revises: 
Create Date: 2025-12-11 16:37:54.862261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e766313e36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """
    Initial schema adjustments.

    This migration is intentionally idempotent to accommodate legacy dev DBs
    that were mutated outside Alembic (e.g. prior runtime ALTER TABLE hacks).
    """
    bind = op.get_bind()
    insp = sa.inspect(bind)

    # trade_plans: add FK if not already present
    if insp.has_table('trade_plans'):
        existing_fks = {fk.get('name') for fk in insp.get_foreign_keys('trade_plans')}
        if 'fk_trade_plans_executed_trade_id' not in existing_fks:
            with op.batch_alter_table('trade_plans', schema=None) as batch_op:
                batch_op.create_foreign_key(
                    'fk_trade_plans_executed_trade_id',
                    'trades',
                    ['executed_trade_id'],
                    ['id'],
                )

    # users: add subscription columns if missing
    if insp.has_table('users'):
        existing_user_cols = {c['name'] for c in insp.get_columns('users')}
        with op.batch_alter_table('users', schema=None) as batch_op:
            if 'subscription_tier' not in existing_user_cols:
                batch_op.add_column(sa.Column('subscription_tier', sa.String(length=20), nullable=True))
            if 'subscription_status' not in existing_user_cols:
                batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=True))
            if 'trial_ends_at' not in existing_user_cols:
                batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
            if 'subscription_expires_at' not in existing_user_cols:
                batch_op.add_column(sa.Column('subscription_expires_at', sa.DateTime(), nullable=True))
            if 'stripe_customer_id' not in existing_user_cols:
                batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('subscription_expires_at')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('subscription_tier')

    with op.batch_alter_table('trade_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
